/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ManagerBreadcrumb {
        "elements": any[];
    }
}
declare global {
    interface HTMLManagerBreadcrumbElement extends Components.ManagerBreadcrumb, HTMLStencilElement {
    }
    var HTMLManagerBreadcrumbElement: {
        prototype: HTMLManagerBreadcrumbElement;
        new (): HTMLManagerBreadcrumbElement;
    };
    interface HTMLElementTagNameMap {
        "manager-breadcrumb": HTMLManagerBreadcrumbElement;
    }
}
declare namespace LocalJSX {
    interface ManagerBreadcrumb {
        "elements"?: any[];
    }
    interface IntrinsicElements {
        "manager-breadcrumb": ManagerBreadcrumb;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "manager-breadcrumb": LocalJSX.ManagerBreadcrumb & JSXBase.HTMLAttributes<HTMLManagerBreadcrumbElement>;
        }
    }
}
